name: Generate NOTICE_MIGRATION.md

on:
  release:
    types: [ prereleased, released ]

jobs:
  generate_notice_migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r scripts/notice-migration-generator/requirements.txt
      - name: Validate python version
        run: which python3
      - name: Run script
        run: python3 scripts/notice-migration-generator/notice_migration_generator.py -r ${{ github.event.release.tag_name }}