name: Generate NOTICE_MIGRATION.md

on:
  release:
    types: [ prereleased, released ]

jobs:
  generate_notice_migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r scripts/notice-migration-generator/requirements.txt

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Get previous release version
        run: python3 scripts/notice-migration-generator/get_previous_release.py

      - name: Checkout previous version
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PREVIOUS_VERSION }}

      - name: Generate previous rules.json
        run: ./gradlew webClientRulesJSON

      - name: Upload previous rules.json
        uses: actions/upload-artifact@v3
        with:
          name: rules-2.json
          path: web/client/static/rules.json

      - name: Checkout current version
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate current rules.json
        run: ./gradlew webClientRulesJSON

      - name: Upload current rules.json
        uses: actions/upload-artifact@v3
        with:
          name: rules-1.json
          path: web/client/static/rules.json

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Validate download
        run: ls -la *.json

      - name: Run script
        run: python3 scripts/notice-migration-generator/notice_migration_generator.py -r ${{ github.event.release.tag_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: master
          commit-message: "docs: Automatic update of NOTICE_MIGRATION.md"
          title: "docs: Automatic update of NOTICE_MIGRATION.md"
          delete-branch: true
          add-paths: docs/*.md
