name: Upload Release Assets

on:
  release:
    types: [ prereleased, released ]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  upload-release-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Pwd
        run: ls -la ./cli/build/libs/gtfs-validator-*.jar

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cli/build/libs/gtfs-validator-${{ github.event.release.tag_name }}-SNAPSHOT-cli.jar
          asset_name: gtfs-validator-${{ github.event.release.tag_name }}-SNAPSHOT-cli.jar
          asset_content_type: application/java-archive
